[package]
name = "usage-tracker"
version = "0.1.0"
edition = "2024"
authors = ["HExEN"]
description = "A lightweight Windows application usage tracker."
homepage = "https://github.com/HexCore99/usage-tracker"
repository = "https://github.com/HexCore99/usage-tracker"

[package.metadata.wix]
eula = false

[dependencies]
windows = { version = "0.58", features = [
  "Win32_UI_WindowsAndMessaging",
  "Win32_Foundation",
  "Win32_System_Threading",
  "Win32_System_ProcessStatus",
  "Win32_System_Diagnostics_ToolHelp",
  "Win32_Security",
  "Win32_Storage_FileSystem",
] }
sysinfo = "0.30"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
dirs = "5"
winreg = "0.52"
